version: '3.8'
services:
  # gpi-pfe-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: gpi-nest-api
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - gpi-pfe
  #   env_file:
  #     - .env

  gpi-pfe:
    image: mysql:8
    container_name: gpidb
    restart: always
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - gpi-pfe:/var/lib/mysql

volumes:
  gpi-pfe:
    name: gpi-pfe-db
