import { PrismaClient } from '@prisma/client';
import  * as bcrypt from 'bcrypt'
const prisma = new PrismaClient();

async function seed() {
  await prisma.societe.createMany({
    data: [
      {
        raisonSociale: 'NetUse',
        adresse: 'Centre Urbain Nord',
        responsable: 'AbdelAziz KRAIDI',
        email: 'contact@netuse.com.tn',
        numtel: '71948225',
        secteurActivite: 'Prestataire de service',
        typeSociete: 'FOURNISSEUR_PRESTATAIRE',
      },
      {
        raisonSociale: 'Intelo',
        adresse: 'Alain SAVARY',
        responsable: 'Koussay',
        email: 'contact@intelo.com.tn',
        numtel: '71850600',
        secteurActivite: 'Vente Matériels informatique',
        typeSociete: 'FOURNISSEUR',
      },
      {
        raisonSociale: 'Infolog',
        adresse: 'Alain SAVARY',
        responsable: 'Sami',
        email: 'contact@infolog.com.tn',
        numtel: '71123456',
        secteurActivite: 'Vente Matériels informatique',
        typeSociete: 'FOURNISSEUR',
      },
      {
        raisonSociale: 'SPG',
        adresse: 'Lac',
        responsable: 'Khaled',
        email: 'contact@spg.com.tn',
        numtel: '70456789',
        secteurActivite:
          'Sécurité Informatique solution de sauvegarde et antivirus',
        typeSociete: 'FOURNISSEUR_PRESTATAIRE',
      },
      {
        raisonSociale: 'Brain Informatique',
        adresse: 'Place Pasteur',
        responsable: 'Taieb',
        email: 'contact@brain.com.tn',
        numtel: '70987321',
        secteurActivite: 'Vente Matériels informatique',
        typeSociete: 'FOURNISSEUR',
      },
      {
        raisonSociale: 'CIC',
        adresse: 'Tunis',
        responsable: 'PDG',
        email: 'contact@cic.com.tn',
        numtel: '70147258',
        secteurActivite: "Vente Toners et Cartouches d'encre",
        typeSociete: 'FOURNISSEUR',
      },
      {
        raisonSociale: 'RobotBat Afrique',
        adresse: 'El Manar',
        responsable: 'Hechemi KEBOUBI',
        email: 'contact@robotbatafrique.com.tn',
        numtel: '70549821',
        secteurActivite: 'Vente Logiciels Techniques',
        typeSociete: 'FOURNISSEUR',
      },
    ],
  });

  await prisma.departement.createMany({
    data: [
      {
        idDepartement: 'DG',
        nom: 'Direction Générale',
      },
      {
        idDepartement: 'DC',
        nom: 'Département Commercial',
      },
      {
        idDepartement: 'DAF',
        nom: 'Département Administratif et Financier',
      },
      {
        idDepartement: 'DI',
        nom: 'Département Ingénierie',
      },
      {
        idDepartement: 'DDPOC',
        nom: 'Département Développement, Partenariat, Opérations et Conseils',
      },
    ],
  });

  await prisma.specialite.createMany({
    data: [
      {
        idSpecialite: 'DG',
        nom: 'Directeur Général',
        idDepartement: 'DG',
      },
      {
        idSpecialite: 'IT_ADMIN',
        nom: 'Administrateur Système',
        idDepartement: 'DC',
      },
      {
        idSpecialite: 'ChDC',
        nom: 'Chef de Département DC',
        idDepartement: 'DG',
      },
      {
        idSpecialite: 'ACP',
        nom: 'Achat et Procurement',
        idDepartement: 'DC',
      },
      {
        idSpecialite: 'GC',
        nom: 'Génie Civile',
        idDepartement: 'DI',
      },
      {
        idSpecialite: 'CHM',
        nom: 'Charpente Métallique',
        idDepartement: 'DI',
      },
      {
        idSpecialite: 'Elec',
        nom: 'Electrique',
        idDepartement: 'DI',
      },
      {
        idSpecialite: 'ETG',
        nom: 'Etude Générale',
        idDepartement: 'DI',
      },
      {
        idSpecialite: 'MEC',
        nom: 'Mécanique',
        idDepartement: 'DI',
      },
      {
        idSpecialite: 'HSE',
        nom: 'Hygiène Sécurité et Environnement',
        idDepartement: 'DI',
      },
      {
        idSpecialite: 'SRG',
        nom: 'Services Généraux',
        idDepartement: 'DAF',
      },
      {
        idSpecialite: 'ORD',
        nom: 'Ordonnancement',
        idDepartement: 'DDPOC',
      },
      {
        idSpecialite: 'ARCH',
        nom: 'Archivage',
        idDepartement: 'DDPOC',
      },
    ],
  });
  const salt= await bcrypt.genSalt()
  const hashedPassword=await bcrypt.hash('123', salt)
  await prisma.utilisateur.createMany({
    data: [
      {
        idUtilisateur: 616,
        password:hashedPassword,
        fullName: 'Kheireddine MHAMDI',
        email: 'kh.mhamdi@teci.com.tn',
        createdAt: new Date(),
        lastLogin: null,
        roleUtilisateur: 'ADMINISTRATEUR',
        etatUtilisateur: 'actif',
        telFix: '924',
        telMobile: '53722910',
        idSpecialite: 'IT_ADMIN',
      },
      {
        idUtilisateur: 617,
        password:hashedPassword,
        fullName: 'Lotfi DELLAI',
        email: 'dli@teci.com.tn',
        createdAt: new Date(),
        lastLogin: null,
        roleUtilisateur: 'EMPLOYE',
        etatUtilisateur: 'actif',
        telFix: '948',
        telMobile: '',
        idSpecialite: 'GC',
      },
      {
        idUtilisateur: 470,
        password:hashedPassword,
        fullName: 'Mohamed Yacine HBAILI',
        email: 'my.hbaili@teci.com.tn',
        createdAt: new Date(),
        lastLogin: null,
        roleUtilisateur: 'EMPLOYE',
        etatUtilisateur: 'actif',
        telFix: '940',
        telMobile: '',
        idSpecialite: 'ORD',
      },
      {
        idUtilisateur: 448,
        password:hashedPassword,
        fullName: 'Sami ABDELLAH',
        email: 'smi@teci.com.tn',
        createdAt: new Date(),
        lastLogin: null,
        roleUtilisateur: 'EMPLOYE',
        etatUtilisateur: 'actif',
        telFix: '923',
        telMobile: '',
        idSpecialite: 'ARCH',
      },
      {
        idUtilisateur: 450,
        password:hashedPassword,
        fullName: 'Nedra KARAOULI',
        email: 'kar@teci.com.tn',
        createdAt: new Date(),
        lastLogin: null,
        roleUtilisateur: 'EMPLOYE',
        etatUtilisateur: 'actif',
        telFix: '913',
        telMobile: '',
        idSpecialite: 'SRG',
      },
    ],
  });

  await prisma.materiel.createMany({
    data: [
      {
        numeroSerie: 'CZC7367N7F',
        categorie: 'UniteCentrale',
        marque: 'HP',
        modele: 'ProDesk 400 G4 MT',
        prix: 2000,
        garantie: '1',
        etatMateriel: 'fonctionnel',
        dateAcquisition: new Date('2018-12-28'),
        disponibilite: 'Affecté',
        nombrePortSwitch: null,
        debitSwitch: null,
        technologieSwitch: null,
        processeurPC: '3.6 Ghz',
        memoireCache: '8 Mo',
        ram: '8 Go',
        disque: '1*SSD 256 Go + 1*HDD 1To',
        carteGraphique: '2 Go',
        nombreDisque: '2',
        tailleEcran: null,
        etatBatteriePcPortable: null,
        vitesseImpression: null,
        connexionWLU: null,
        technologieOnduleur: null,
        fonctionSupplementaireScanImp: null,
        vitesseScanner: null,
        typeScanner: null,
        resolutionScanImpVideoP: null,
        technologieImpression: null,
        formatScanImp: null,
        poidsOnduleur: null,
        autonomieOnduleur: null,
        capaciteChargeOnduleur: null,
        entreeHDMI_VideoProjecteur: false,
        entreeVGA_VideoProjecteur: false,
        entreeUSB_VideoProjecteur: false,
        entreeLAN_VideoProjecteur: false,
        idSociete: 2,
      },
      {
        numeroSerie: '124Q08KU',
        categorie: 'Ecran',
        marque: 'DELL',
        modele: 'P2412Hb',
        prix: 800,
        garantie: '1',
        etatMateriel: 'fonctionnel',
        dateAcquisition: new Date('2012-03-24'),
        disponibilite: 'Affecté',
        nombrePortSwitch: null,
        debitSwitch: null,
        technologieSwitch: null,
        processeurPC: null,
        memoireCache: null,
        ram: null,
        disque: null,
        carteGraphique: null,
        nombreDisque: null,
        tailleEcran: 24,
        etatBatteriePcPortable: null,
        vitesseImpression: null,
        connexionWLU: null,
        technologieOnduleur: null,
        fonctionSupplementaireScanImp: null,
        vitesseScanner: null,
        typeScanner: null,
        resolutionScanImpVideoP: null,
        technologieImpression: null,
        formatScanImp: null,
        poidsOnduleur: null,
        autonomieOnduleur: null,
        capaciteChargeOnduleur: null,
        entreeHDMI_VideoProjecteur: false,
        entreeVGA_VideoProjecteur: false,
        entreeUSB_VideoProjecteur: false,
        entreeLAN_VideoProjecteur: false,
        idSociete: 2,
      },
      {
        numeroSerie: '124Q07PU',
        categorie: 'Ecran',
        marque: 'DELL',
        modele: 'P2412Hb',
        prix: 800,
        garantie: '1',
        etatMateriel: 'fonctionnel',
        dateAcquisition: new Date('2012-03-24'),
        disponibilite: 'Disponible',
        nombrePortSwitch: null,
        debitSwitch: null,
        technologieSwitch: null,
        processeurPC: null,
        memoireCache: null,
        ram: null,
        disque: null,
        carteGraphique: null,
        nombreDisque: null,
        tailleEcran: 24,
        etatBatteriePcPortable: null,
        vitesseImpression: null,
        connexionWLU: null,
        technologieOnduleur: null,
        fonctionSupplementaireScanImp: null,
        vitesseScanner: null,
        typeScanner: null,
        resolutionScanImpVideoP: null,
        technologieImpression: null,
        formatScanImp: null,
        poidsOnduleur: null,
        autonomieOnduleur: null,
        capaciteChargeOnduleur: null,
        entreeHDMI_VideoProjecteur: false,
        entreeVGA_VideoProjecteur: false,
        entreeUSB_VideoProjecteur: false,
        entreeLAN_VideoProjecteur: false,
        idSociete: 2,
      },
      {
        numeroSerie: '5CD5502STZ',
        categorie: 'PcPortable',
        marque: 'HP',
        modele: 'PAVILION Gaming 15-AK000NK',
        prix: 1790,
        garantie: '1',
        etatMateriel: 'fonctionnel',
        dateAcquisition: new Date('2017-02-22'),
        disponibilite: 'Emprunté',
        nombrePortSwitch: null,
        debitSwitch: null,
        technologieSwitch: null,
        processeurPC: '2.6 Ghz',
        memoireCache: '8 Mo',
        ram: '16 Go',
        disque: '1*SSD 2.5" 480 Go + 1*SSD M2 480 Go',
        carteGraphique: '4 Go',
        nombreDisque: '2',
        tailleEcran: 15.6,
        etatBatteriePcPortable: 'morte',
        vitesseImpression: null,
        connexionWLU: null,
        technologieOnduleur: null,
        fonctionSupplementaireScanImp: null,
        vitesseScanner: null,
        typeScanner: null,
        resolutionScanImpVideoP: null,
        technologieImpression: null,
        formatScanImp: null,
        poidsOnduleur: null,
        autonomieOnduleur: null,
        capaciteChargeOnduleur: null,
        entreeHDMI_VideoProjecteur: false,
        entreeVGA_VideoProjecteur: false,
        entreeUSB_VideoProjecteur: false,
        entreeLAN_VideoProjecteur: false,
        idSociete: 2,
      },
      {
        numeroSerie: 'V1N5X02990',
        categorie: 'Imprimante',
        marque: 'Kyocera',
        modele: 'FS-2100 DN',
        prix: 680,
        garantie: '1',
        etatMateriel: 'fonctionnel',
        dateAcquisition: new Date('2015-02-22'),
        disponibilite: 'Disponible',
        nombrePortSwitch: null,
        debitSwitch: null,
        technologieSwitch: null,
        processeurPC: null,
        memoireCache: null,
        ram: null,
        disque: null,
        carteGraphique: null,
        nombreDisque: null,
        tailleEcran: null,
        etatBatteriePcPortable: null,
        vitesseImpression: '50 ppm',
        connexionWLU: 'LAN',
        technologieOnduleur: null,
        fonctionSupplementaireScanImp: null,
        vitesseScanner: null,
        typeScanner: null,
        resolutionScanImpVideoP: null,
        technologieImpression: 'Laser',
        formatScanImp: 'A4',
        poidsOnduleur: null,
        autonomieOnduleur: null,
        capaciteChargeOnduleur: null,
        entreeHDMI_VideoProjecteur: false,
        entreeVGA_VideoProjecteur: false,
        entreeUSB_VideoProjecteur: false,
        entreeLAN_VideoProjecteur: false,
        idSociete: 5,
      },
      {
        numeroSerie: 'BWVGWY1',
        categorie: 'PcPortable',
        marque: 'DELL',
        modele: 'Inspiron 15 - 3537',
        prix: 1500,
        garantie: '1',
        etatMateriel: 'fonctionnel',
        dateAcquisition: new Date('2014-03-22'),
        disponibilite: 'Disponible',
        nombrePortSwitch: null,
        debitSwitch: null,
        technologieSwitch: null,
        processeurPC: '2.6 Ghz',
        memoireCache: '8 Mo',
        ram: '8 Go',
        disque: '500 Go HDD',
        carteGraphique: '2 Go',
        nombreDisque: '1',
        tailleEcran: 15.6,
        etatBatteriePcPortable: 'Fonctionnelle',
        vitesseImpression: null,
        connexionWLU: null,
        technologieOnduleur: null,
        fonctionSupplementaireScanImp: null,
        vitesseScanner: null,
        typeScanner: null,
        resolutionScanImpVideoP: null,
        technologieImpression: null,
        formatScanImp: null,
        poidsOnduleur: null,
        autonomieOnduleur: null,
        capaciteChargeOnduleur: null,
        entreeHDMI_VideoProjecteur: false,
        entreeVGA_VideoProjecteur: false,
        entreeUSB_VideoProjecteur: false,
        entreeLAN_VideoProjecteur: false,
        idSociete: 3,
      },
    ],
  });

  await prisma.affectation.createMany({
    data: [
      {
        idUtilisateur: 616,
        numeroSerie: 'CZC7367N7F',
        dateAttribution: new Date('2018-12-28'),
        dateRetour: null,
        motifRetour: null,
      },
      {
        idUtilisateur: 616,
        numeroSerie: '124Q08KU',
        dateAttribution: new Date('2018-12-28'),
        dateRetour: null,
        motifRetour: null,
      },
    ],
  });

  await prisma.emprunt.create({
    data: {
      idUtilisateur: 616,
      numeroSerie: '5CD5502STZ',
      dateEmprunt: new Date(),
      dateRestitution: null,
      refProjet: 'TERG910',
      etatMatRestitution: '',
    },
  });

  await prisma.stocks.createMany({
    data: [
      {
        refArt: 'TK3100',
        categorie: 'Toner',
        marque: 'Kyocera',
        modele: 'FS-2100 DN',
        prix: 400,
        quantiteStock: 4,
        capaciteToner: 12500,
        compatibiliteToner: '',
        couleurToner: 'NOIR',
        capaciteFlashDvdCdRamHDD: null,
        typeDisqueStockage: null,
        typeConnexionClavierSouris: null,
        dispositionToucheClavier: null,
        nombreBouttonSouris: null,
        memoireCarteGraphiqueRam: null,
        IntefaceCarteGraphique: null,
        frequenceCarteGraphiqueRam: null,
        typeRam: null,
        interFaceHDD: null,
        vitesseHDD: null,
        tailleHDD: null,
        TypeHDD: null,
        autre: null,
      },
      {
        refArt: 'DISKEXT2T',
        categorie: 'DisqueDurExterne',
        marque: 'Seagate ',
        modele: '1TEAP6-500',
        prix: 256,
        quantiteStock: 1,
        capaciteToner: null,
        compatibiliteToner: null,
        couleurToner: null,
        capaciteFlashDvdCdRamHDD: 2,
        typeDisqueStockage: null,
        typeConnexionClavierSouris: null,
        dispositionToucheClavier: null,
        nombreBouttonSouris: null,
        memoireCarteGraphiqueRam: null,
        IntefaceCarteGraphique: null,
        frequenceCarteGraphiqueRam: null,
        typeRam: null,
        interFaceHDD: null,
        vitesseHDD: 5400,
        tailleHDD: '2.5 pouces',
        TypeHDD: 'HDD',
        autre: null,
      },
    ],
  });

  await prisma.alimentation.createMany({
    data: [
      {
        idSociete: 6,
        refArt: 'TK3100',
        dateAlimentation: new Date('2024-04-14'),
        quantiteAlimente: 5,
      },
      {
        idSociete: 2,
        refArt: 'DISKEXT2T',
        dateAlimentation: new Date('2022-02-22'),
        quantiteAlimente: 1,
      },
    ],
  });

  await prisma.consommation.createMany({
    data: [
      {
        idUtilisateur: null,
        refArt: 'TK3100',
        numeroSerie: 'V1N5X02990',
        dateConsommation: new Date('2024-04-15'),
        quantiteConsomme: 1,
      },
      {
        idUtilisateur: 616,
        refArt: 'DISKEXT2T',
        numeroSerie: null,
        dateConsommation: new Date('2023-08-10'),
        quantiteConsomme: 1,
      },
    ],
  });

  await prisma.logiciel.createMany({
    data: [
      {
        libelle: 'Autocad',
        version: '2024',
        editeur: 'AutoDesk',
        dateAcquisition: new Date('2024-01-02'),
        typeLogiciel: 'Technique',
        idSociete: 7,
      },
      {
        libelle: 'MS Office 365',
        version: '2024',
        editeur: 'Microsoft',
        dateAcquisition: new Date('2024-01-02'),
        typeLogiciel: 'Bureautique',
        idSociete: 1,
      },
    ],
  });

  await prisma.licence.createMany({
    data: [
      {
        numeroLicence: '456-98765431 / 001D1',
        dateActivation: new Date('2024-01-02'),
        dateExpiration: new Date('2024-12-31'),
        prixLicence: 7500,
        statutLicence: 'Assignée',
        idLogiciel: 1,
      },
      {
        numeroLicence: '456-98765432 / 001D1',
        dateActivation: new Date('2024-01-02'),
        dateExpiration: new Date('2024-12-31'),
        prixLicence: 7500,
        statutLicence: 'Disponible',
        idLogiciel: 1,
      },
      {
        numeroLicence: '456-98765433 / 001D1',
        dateActivation: new Date('2024-01-02'),
        dateExpiration: new Date('2024-12-31'),
        prixLicence: 7500,
        statutLicence: 'Disponible',
        idLogiciel: 1,
      },
      {
        numeroLicence: '456-98765434 / 001D1',
        dateActivation: new Date('2024-01-02'),
        dateExpiration: new Date('2024-12-31'),
        prixLicence: 7500,
        statutLicence: 'Disponible',
        idLogiciel: 1,
      },
      {
        numeroLicence: '456-98765435 / 001D1',
        dateActivation: new Date('2024-01-02'),
        dateExpiration: new Date('2024-12-31'),
        prixLicence: 7500,
        statutLicence: 'Disponible',
        idLogiciel: 1,
      },
      {
        numeroLicence: 'AERED-FDF56-DDF87-32SCX-DF2G5',
        dateActivation: new Date('2024-01-02'),
        dateExpiration: new Date('2024-12-31'),
        prixLicence: 500,
        statutLicence: 'Assignée',
        idLogiciel: 2,
      },
      {
        numeroLicence: '87FTH-TFG25-6S5G7-NJK36-HJKLQ',
        dateActivation: new Date('2024-01-02'),
        dateExpiration: new Date('2024-12-31'),
        prixLicence: 500,
        statutLicence: 'Disponible',
        idLogiciel: 2,
      },
    ],
  });

  await prisma.installation.createMany({
    data: [
      {
        numeroSerie: 'CZC7367N7F',
        idLicence: 1,
        dateInstallation: new Date('2024-06-01'),
        dateDesinstallation: new Date('2024-06-30'),
        etatOperation: 'Désinstallée',
      },
      {
        numeroSerie: '5CD5502STZ',
        idLicence: 1,
        dateInstallation: new Date('2024-06-30'),
        dateDesinstallation: null,
        etatOperation: "En cours d'utilisation",
      },
      {
        numeroSerie: 'CZC7367N7F',
        idLicence: 6,
        dateInstallation: new Date('2024-01-02'),
        dateDesinstallation: null,
        etatOperation: "En cours d'utilisation",
      },
    ],
  });
}

seed()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
